---
services:
  db:
    image: raghuram0024/pythonapp:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  auth_service:
    image: raghuram0024/pythonapp:authimage
    ports:
      - "5001:5001"
    deploy:
      replicas: 1

  book_service:
    image: raghuram0024/pythonapp:bookimage
    ports:
      - "5002:5002"
    deploy:
      replicas: 1

  borrow_service:
    image: raghuram0024/pythonapp:borrowimage
    ports:
      - "5003:5003"
    deploy:
      replicas: 1

  frontend:
    image: raghuram0024/pythonapp:appimage
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
